name: go-cards  # compose project name

# https://docs.docker.com/reference/compose-file/services/
services:
  cards:
    image: mziemianek/cards-svc:v1
    build:
      context: ./services/cards
    container_name: cards-svc
    # command: [
    # ]
    ports:
      - "8080:8080"
